-- INIT BRAND
CREATE TABLE IF NOT EXISTS BRAND(
  ID INT PRIMARY KEY,
  NAME VARCHAR(36) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT current_timestamp(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT current_timestamp()
);
INSERT INTO BRAND(ID,NAME,DESCRIPTION)
VALUES(1,'Brand-sample','Brand name created to simulate the brand name to which the prices point');
-- END BRAND

--We keep the requested date format,
--for this we use varchar and later we will make the queries by parsing to date

-- INIT PRICES
CREATE TABLE IF NOT EXISTS PRICES (
  ID UUID PRIMARY KEY,
  BRAND_ID INT NOT NULL,
  START_DATE VARCHAR(19) NOT NULL,
  END_DATE VARCHAR(19) NOT NULL,
  PRICE_LIST INT NOT NULL,
  PRODUCT_ID INT NOT NULL,
  PRIORITY TINYINT NOT NULL DEFAULT 0,
  PRICE DECIMAL(10,2) NOT NULL,
  CURR VARCHAR(3) NOT NULL DEFAULT 'EUR',
  CREATED_AT TIMESTAMP NOT NULL DEFAULT current_timestamp(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT current_timestamp(),
  CONSTRAINT fk_prices_brand FOREIGN KEY (BRAND_ID) REFERENCES BRAND (ID)
);
-- INIT BRAND
